version : '3'
services :
  phpredisadmin:
    build: ./phpredisadmin
    container_name: redis-admin
    ports:
    - "16379:80"
    environment:
    - REDIS_1_HOST=redis-6379
    - REDIS_1_PORT=6379
    networks:
    - redis_redis-net
networks: # 创建网络
  redis_redis-net:
    external: true