version : '3'
services :
  phpmyadmin:
    build: ./phpmyadmin
    container_name: dll-mysql-admin
    ports:
    - "13306:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "123456"
      PMA_HOST: dll-mysql-master
    networks:
    - dll-mysql_dll-mysql-net
networks: # 创建网络
  dll-mysql_dll-mysql-net:
    external: true